package com.fj.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2017-10-07T15:35:12.363+08:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://cxf.fj.com/", name = "MyCXF")
@XmlSeeAlso({})
public interface MyCXF {

    @WebMethod
    @RequestWrapper(localName = "getAge", targetNamespace = "http://cxf.fj.com/", className = "com.fj.cxf.GetAge")
    @ResponseWrapper(localName = "getAgeResponse", targetNamespace = "http://cxf.fj.com/", className = "com.fj.cxf.GetAgeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getAge(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
